# Generated by Django 5.2.4 on 2025-07-16 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("clients", "0001_initial"),
        ("contracts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Request",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("standard", "Стандартен анекс"),
                            ("deletion", "Анекс за заличаване на обезпечение"),
                        ],
                        max_length=20,
                    ),
                ),
                ("preparation_date", models.DateField(blank=True, null=True)),
                ("correction_required", models.BooleanField(blank=True, null=True)),
                ("signing_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "В процес на работа"),
                            ("signed", "Подписан"),
                            ("rejected", "Отказан"),
                        ],
                        default="in_progress",
                        max_length=20,
                    ),
                ),
                (
                    "request_number",
                    models.CharField(blank=True, max_length=30, null=True, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="clients.client"
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="contracts.currency",
                    ),
                ),
                (
                    "loan_agreement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contracts.contract",
                    ),
                ),
            ],
        ),
    ]
