# Generated by Django 5.2.4 on 2025-07-25 20:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("loan_requests", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="request",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
