# Generated by Django 5.2.4 on 2025-07-19 12:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NewsPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Заглавие")),
                ("content", models.TextField(verbose_name="Съдържание")),
                (
                    "published_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Дата на публикуване",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активна новина"),
                ),
            ],
            options={
                "verbose_name": "Новина",
                "verbose_name_plural": "Новини",
                "ordering": ["-published_at"],
            },
        ),
    ]
