# Generated by Django 5.2.4 on 2025-07-06 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("clients", "0004_alter_client_town"),
    ]

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "currency_code",
                    models.CharField(
                        max_length=3, unique=True, verbose_name="валута код"
                    ),
                ),
                (
                    "currency_name",
                    models.CharField(max_length=10, verbose_name="валута име"),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="LoanType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "loan_type",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="вид на кредита"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contract_number",
                    models.CharField(
                        help_text="Номер на Договора за кредит.",
                        max_length=20,
                        unique=True,
                        verbose_name="Договор номер",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="дата")),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clients.client",
                        verbose_name="Клиент (ЕИК)",
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        default="EUR",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contracts.currency",
                        verbose_name="валута",
                    ),
                ),
                (
                    "loan_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contracts.loantype",
                        verbose_name="вид на кредита",
                    ),
                ),
            ],
        ),
    ]
