# Generated by Django 5.2.4 on 2025-07-25 19:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="signaturelog",
            name="is_signed_successfully",
            field=models.BooleanField(default=False),
        ),
    ]
