# Generated by Django 5.2.4 on 2025-07-25 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_signaturelog_is_signed_successfully"),
        ("loan_requests", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="signaturelog",
            name="request",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="loan_requests.request",
            ),
        ),
    ]
