# Generated by Django 5.2.4 on 2025-07-05 18:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="represented_together",
            field=models.BooleanField(
                default=False, verbose_name="Фирмата се представлява съвместно от двама"
            ),
        ),
    ]
