# Generated by Django 5.2.4 on 2025-07-05 21:30

import clients.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0002_alter_client_represented_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="eik",
            field=models.CharField(
                help_text="Единен идентификационен код (само цифри).",
                max_length=20,
                unique=True,
                validators=[clients.validators.validate_eik_only_digits],
                verbose_name="ЕИК",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="number",
            field=models.CharField(
                blank=True, default="", max_length=10, verbose_name="номер"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="client",
            name="town",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="clients.town",
                verbose_name="град/село",
            ),
        ),
    ]
