# Generated by Django 5.2.4 on 2025-07-06 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0003_alter_client_eik_alter_client_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="town",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="clients.town",
                verbose_name="град",
            ),
        ),
    ]
