# Generated by Django 5.2.4 on 2025-07-16 16:34

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GeneratedAnnex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("annex_number", models.CharField(max_length=20)),
                ("annex_date", models.DateField()),
                ("file_path", models.FileField(upload_to="annexes/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
