# Generated by Django 5.2.4 on 2025-07-16 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("annexes", "0001_initial"),
        ("loan_requests", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="generatedannex",
            name="request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="generated_annexes",
                to="loan_requests.request",
            ),
        ),
    ]
