# Generated by Django 5.2.4 on 2025-07-10 17:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("requests", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="request",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=datetime.datetime(2025, 7, 9, 8, 0)
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="request",
            name="request_number",
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
