# Generated by Django 5.2.4 on 2025-07-12 18:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("requests", "0002_request_created_at_request_request_number"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="request",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("standard", "Стандартен анекс"),
                    ("deletion", "Анекс за заличаване на обезпечение"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="request",
            name="maker",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_requests",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Изпълнител",
            ),
        ),
    ]
